version: '3'
services:
      api:
            build: .
            depends_on:
                  - postgres
            ports:
                  - 8000:8000
            volumes:
                  - ./:/usr/src/app:ro
            command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
            environment:
                  - DATABASE_HOSTNAME=postgres
                  - DATABASE_PORT=5432
                  - DATABASE_PASSWORD=784512
                  - DATABASE_NAME=fastapi
                  - DATABASE_USERNAME=postgres
                  - SECRET_KEY=50f90f4e05e5c8e6fba8067f50340f7c5a642af66b34a9a7d325e8951ce560e5
                  - ALGORITHM=HS256
                  - ACCESS_TOKEN_EXPIRE_MINUTES=60
      postgres: 
            image: postgres
            environment:
                  - POSTGRES_PASSWORD=784512
                  - POSTGRES_DB=fastapi

            volumes:
                  - postgres-db:/var/lib/postgresql/data

volumes:
      postgres-db:
