"""add phone number

Revision ID: 830a871ef0b2
Revises: bdd9cf46c180
Create Date: 2022-07-28 10:59:44.775213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830a871ef0b2'
down_revision = 'bdd9cf46c180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
